### ISSUE TITLE
Upgrade Julia & package versions

### ISSUE THREAD

**Issue by dpmerrell** [gitter-lab/ssps#16]
Julia has gone from v1.2 to v1.4 in the months since starting this project.

Many of the packages have also released updates in that time.

It's probably best to update the Julia version and *.toml files.

**Comment by agitter** [comment]
We could test that SSPS runs in Julia 1.2 and 1.4.  In Travis CI, we would change
https://github.com/gitter-lab/ssps/blob/3ad15c74f4e2fb377f8b04bde4a4b0275bf702fb/.travis.yml#L7-L8
to
```
julia:
  - 1.2
  - 1.4
```

**Comment by dpmerrell** [comment]
Very cool, I'll add that to the .travis.yml file. I'm making a PR later today which fixes this and one or two other issues.
