### ISSUE TITLE
SSPS output format

### ISSUE THREAD

**Issue by dpmerrell** [gitter-lab/ssps#2]
For one-off SSPS runs: need to convert output JSONs to a tab-delimited file -- one row for each edge.

e.g.,
`node1` (tab) `node2` (tab) `score`

**Comment by agitter** [comment]
That is the format that [GENIE3](https://github.com/vahuynh/GENIE3/blob/master/GENIE3_python/GENIE3_python_doc.pdf) and other bioinformatics methods use, so it is a good choice for SSPS.  I'm assuming that node1 is the parent node and node2 is the child node.

**Comment by dpmerrell** [comment]
Should be fixed on master :heavy_check_mark:
