### ISSUE TITLE
Tracking SSPS versions

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ssps#3]
We should add a version to the SSPS codebase.  This will help report which version of the code was used in manuscripts and track changes between releases.

I haven't looked into best practices for Julia package versions.

**Comment by dpmerrell** [comment]
> I haven't looked into best practices for Julia package versions.

Right, neither have I. I _have_ noticed version-specific branches in the repos for other projects -- which seems like a reasonable way to manage versions. I'll take a look around and let you know what I find.

**Comment by dpmerrell** [comment]
I used Github's release management to tag the current codebase as version  `0.1.0`.

I'll release patches periodically, as issues come up and get resolved.
