### ISSUE TITLE
Clarifying installation instructions

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ssps#4]
I followed the installation instructions on a Windows 10 machine with Git Bash (an environment known to cause issues for some software).  I ran into a few Julia dependencies problems and have other install-related comments.

```
julia> Pkg.instantiate()
ERROR: `BSON` is a direct dependency, but does not appear in the manifest. If you intend `BSON` to be a direct dependency, run `Pkg.resolve()` to populate the manifest. Otherwise, remove `BSON` with `Pkg.rm("BSON")`. Finally, run `Pkg.instantiate()` again.
```

Following those instructions
```
julia> Pkg.resolve()
   Cloning default registries into `C:\Users\agitter\.julia`
   Cloning registry from "https://github.com/JuliaRegistries/General.git"
     Added registry `General` to `C:\Users\agitter\.julia\registries\General`
 Resolving package versions...
ERROR: path C:\Users\agitter\.julia\packages\Gen\eQpFO for package Gen no longer exists. Remove the package or `develop` it at a new path
```

If these could be Windows-related errors, I'll try on a Linux machine instead.

We can also update `$ cd graph-ppl/julia-project` to `$ cd ssps/julia-project` (and the 2 other readme instances of `graph-ppl`).

Because the standalone SSPS run still uses Snakemake, should we insert an optional new step 3 between the current steps 2 and 3 of "Running SSPS"?  It would say if you don't have the Python and Snakemake dependencies, see below for installation instructions.

**Comment by dpmerrell** [comment]
I'm pretty sure the issue is in the `julia-project/*.toml` files (they're kind of like `requires.txt` in a python project). I don't think this is a Windows compatibility problem. I'll sort it out.

> should we insert an optional new step 3 between the current steps 2 and 3 of "Running SSPS"? 

Yeah, the instructions could use a slight refactor/rearrangement. I'll work on it.

**Comment by dpmerrell** [comment]
I updated the *.toml files and the README.txt. I believe this issue is resolved, raise another if you feel otherwise.

**Comment by agitter** [comment]
The reorganization looks good to me.  On Windows, I had errors building `Cairo`, `PackageCompiler`, and `Gtk`.  Rather than debug those errors, I'll work on testing installation on a clean Linux system in #5.

**Comment by agitter** [comment]
Testing #5 in macOS shows errors building `Cairo` and `Gtk` as well.  However, `PackageCompiler` worked: https://travis-ci.com/github/gitter-lab/ssps/builds/165204702#L112
