### ISSUE TITLE
Add test case for expected my_predictions.csv

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ssps#7]
The first test case we create can be an integration test for `my_predictions.csv`.  If we add the expected output to `tests/expected/my_predictions.csv` or somewhere similar, we can check the version created during continuous integration with the version stored in the repository.

Our SINGE [test cases](https://github.com/gitter-lab/SINGE/blob/master/tests/compare_example_output.sh) use the `csvdiff` Python program to compare a predicted and reference edge list.  It has the ability to tolerate floating point differences due to stochastic algorithms.  We could that approach here as well.

**Comment by dpmerrell** [comment]
You're right, a simple test is called for. I'll think about how to do that.

Currently the output lists edges in order of decreasing weight, so either
1. I need to change the output s.t. edges are listed in lexicographic order, or 
2.  output comparison needs to account for inconsistent orderings.

I'll probably take approach (2).

**Comment by agitter** [comment]
We can talk more about the test strategy.  It will depend on what we consider to be normal variation between runs.

If we decide to use the csvdiff utility like the SINGE test linked above, it will take care of the ordering.
