### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ssps#9]
On Windows 10, I was unable to install `snakemake` through conda.  There were not appropriate Windows package versions available in the `bioconda` and `conda-forge` channels for all of the dependencies.  Switching to `snakemake-minimal` worked and suffices for local execution.  `pandas` must be explicitly installed to that conda environment as well because it is no longer a dependency.

I should confirm that `conda install -c bioconda -c conda-forge snakemake-minimal pandas` creates a minimal working environment for SSPS.  Then, we can update the readme.

After #8, I no longer have errors with `Pkg.instantiate()`.  The example in `run_ssps` appears to run correctly and gives the expected output.

**Comment by agitter** [comment]
I confirmed that `$ conda create -n ssps -c bioconda -c conda-forge python=3.7 snakemake-minimal pandas` works and allows me to run SSPS on Windows.  I also included more details about the error when trying to install `snakemake`.

<summary>Snakemake UnsatisfiableError on Windows</summary><details>
$ conda create -n ssps -c bioconda -c conda-forge python=3.7 snakemake
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package vc conflicts for:
python=3.7 -> vc[version='14.*|>=14,<15.0a0|>=14.1,<15.0a0']
Package filechunkio conflicts for:
snakemake -> filechunkio[version='>=1.6']
Package google-cloud-storage conflicts for:
snakemake -> google-cloud-storage
Package ftputil conflicts for:
snakemake -> ftputil[version='>=3.2']
Package networkx conflicts for:
snakemake -> networkx[version='>=2.0']
Package python_abi conflicts for:
python=3.7 -> python_abi=[build=*_cp37m]
Package dropbox conflicts for:
snakemake -> dropbox[version='>=7.2.1']
Package pysftp conflicts for:
snakemake -> pysftp[version='>=0.2.8']
Package jinja2 conflicts for:
snakemake -> jinja2
Package python-irodsclient conflicts for:
snakemake -> python-irodsclient
Package jsonschema conflicts for:
snakemake -> jsonschema
Package pip conflicts for:
python=3.7 -> pip
Package sqlite conflicts for:
python=3.7 -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0']
Package pygraphviz conflicts for:
snakemake -> pygraphviz[version='>=1.5']
Package pandas conflicts for:
snakemake -> pandas
Package vs2015_runtime conflicts for:
python=3.7 -> vs2015_runtime[version='>=14.16.27012,<15.0a0']
Package openssl conflicts for:
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a']
Package aioeasywebdav conflicts for:
snakemake -> aioeasywebdav
Package crc32c conflicts for:
snakemake -> crc32c
Package pygments conflicts for:
snakemake -> pygments
Package snakemake-minimal conflicts for:
snakemake -> snakemake-minimal[version='5.10.0.*|5.11.0.*|5.11.1.*|5.11.2.*|5.12.1.*|5.12.2.*|5.12.3.*|5.13.0.*|5.14.0.*|5.15.0.*|5.16.0.*|5.17.0.*|5.3.0.*|5.3.1.*|5.4.0.*|5.4.1.*|5.4.2.*|5.4.3.*|5.4.4.*|5.4.5.*|5.5.0.*|5.5.1.*|5.5.2.*|5.5.3.*|5.5.4.*|5.6.0.*|5.7.0.*|5.7.1.*|5.7.4.*|5.8.1.*|5.8.2.*|5.9.1.*']
Package psutil conflicts for:
snakemake -> psutil
Package boto3 conflicts for:
snakemake -> boto3
Package imagemagick conflicts for:
snakemake -> imagemagick[version='>=7.0']
</details>

The error persists if I drop the `python=3.7` request.

**Comment by dpmerrell** [comment]
Thanks for working on this!
